import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:tse/Screens/changepassword.dart';

class Autogenerated {
  bool? status;
  String? message;
  Data? data;

  Autogenerated({this.status, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message'];
    data = json['data'] != null ? Data.fromJson(json['data']) : null;
  }
}

class Data {
  String? fatherName;
  String? fatherPhone;
  String? fatherOccupation;
  String? motherName;
  String? motherPhone;
  String? motherOccupation;
  String? guardianName;
  String? guardianIs;
  String? guardianRelation;
  String? guardianPhone;
  String? guardianOccupation;
  String? guardianAddress;
  String? guardianEmail;

  Data({
    this.fatherName,
    this.fatherPhone,
    this.fatherOccupation,
    this.motherName,
    this.motherPhone,
    this.motherOccupation,
    this.guardianName,
    this.guardianIs,
    this.guardianRelation,
    this.guardianPhone,
    this.guardianOccupation,
    this.guardianAddress,
    this.guardianEmail, required String schoolName, required String address, required String phone, required String email, required Object adminSmallLogo,
  });

  Data.fromJson(Map<String, dynamic> json) {
    fatherName = json['father_name'];
    fatherPhone = json['father_phone'];
    fatherOccupation = json['father_occupation'];
    motherName = json['mother_name'];
    motherPhone = json['mother_phone'];
    motherOccupation = json['mother_occupation'];
    guardianName = json['guardian_name'];
    guardianIs = json['guardian_is'];
    guardianRelation = json['guardian_relation'];
    guardianPhone = json['guardian_phone'];
    guardianOccupation = json['guardian_occupation'];
    guardianAddress = json['guardian_address'];
    guardianEmail = json['guardian_email'];
  }


}

class MyProfileScreen extends StatefulWidget {
  @override
  _MyProfileScreenState createState() => _MyProfileScreenState();
}

class _MyProfileScreenState extends State<MyProfileScreen> {
  // late Data profileData;
  late Data profileData = Data(schoolName: 'TechSavvy Senior Secondary School', address: 'MD ROAD, NORTH HAIBARGAON', phone: '9401876084', email: 'principal.conceptjrcollege@gmail.com', adminSmallLogo: 'https://school.h24x7.in/1693901130-135678882464f6e14a7e89a!favicon.png');

  Future<void> fetchProfileData() async {
    final response = await http.get(Uri.parse('https://school.h24x7.in/api/parent/profile'));

    if (response.statusCode == 200) {
      final jsonData = json.decode(response.body);
      final autogenerated = Autogenerated.fromJson(jsonData);
      setState(() {
        profileData = autogenerated.data!;
      });
    } else {
      throw Exception('Failed to load profile data');
    }
  }

  @override
  void initState() {
    super.initState();
    fetchProfileData();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('My Profile',style: TextStyle(color: Colors.lightGreen),),
        backgroundColor: Colors.blueGrey,
      ),
      body: profileData == null
          ? Center(child: CircularProgressIndicator())
          : Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Card(
              elevation: 5,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(20),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Container(
                    width: double.infinity,
                    decoration: BoxDecoration(
                      color: Colors.blueGrey.withOpacity(0.1), // Highlight color
                      borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
                    ),
                    padding: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                    child: Text(
                      'Student Details',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                        color: Colors.blueGrey,
                      ),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              decoration: BoxDecoration(
                                shape: BoxShape.circle,
                                border: Border.all(
                                  color: Colors.blueGrey.shade200,
                                  width: 3,
                                ),
                              ),
                              child: CircleAvatar(
                                radius: 40,
                                backgroundImage: AssetImage('images/person.png'),
                              ),
                            ),
                            SizedBox(width: 20),
                            Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text('Student Name',
                                    style: TextStyle(
                                        fontSize: 16, fontWeight: FontWeight.bold)),
                                SizedBox(height: 4),
                                Text('Admission No.'),
                                Text('Class:'),
                                Text('Roll No.'),
                                Text('RTE:'),
                                Text('Section: '),
                                Text('Gender: '),
                                Text('Barcode:')
                              ],
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),

            SizedBox(height: 10),
            Card(
              elevation: 5,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(20),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Container(
                    width: double.infinity,
                    decoration: BoxDecoration(
                      color: Colors.blueGrey.withOpacity(0.1), // Highlight color
                      borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
                    ),
                    padding: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                    child: Text(
                      'Address',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                        color: Colors.blueGrey,
                      ),
                    ),
                  ),
                  SizedBox(height: 12),
                  Padding(
                    padding: const EdgeInsets.only(left: 16.0),
                    child: Text('Current Address:'),
                  ),
                  Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Text('Permanent Address:'),
                  ),
                ],
              ),
            ),
            SizedBox(height: 10),
            Card(
              elevation: 5,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(20),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Container(
                    width: double.infinity,
                    decoration: BoxDecoration(
                      color: Colors.blueGrey.withOpacity(0.1), // Highlight color
                      borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
                    ),
                    padding: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                    child: Text(
                      'Parent Guardian Detail',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                        color: Colors.blueGrey,
                      ),
                    ),
                  ),
                  SizedBox(height: 12),
                  Padding(
                    padding: const EdgeInsets.only(left: 16.0,bottom: 10),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text("Father's Name: ${profileData.fatherName ?? ''}"),
                        Text("Mother's Name: ${profileData.motherName ?? ''}"),
                        Text("Father's Phone No.: ${profileData.fatherPhone ?? ''}"),
                        Text("Mother's Phone No.: ${profileData.motherPhone ?? ''}"),
                        Text("Father's Occupation: ${profileData.fatherOccupation ?? ''}"),
                        Text("Mother's Occupation: ${profileData.motherOccupation ?? ''}"),
                        Text("Guardian Name: ${profileData.guardianName ?? ''}"),
                        Text("Guardian Is: ${profileData.guardianIs ?? ''}"),
                        Text("Guardian Relation: ${profileData.guardianRelation ?? ''}"),
                        Text("Guardian Phone: ${profileData.guardianPhone ?? ''}"),
                        Text("Guardian Occupation: ${profileData.guardianOccupation ?? ''}"),
                        Text("Guardian Address: ${profileData.guardianAddress ?? ''}"),
                        Text("Guardian Email: ${profileData.guardianEmail ?? ''}"),
                      ],
                    ),
                  ),
                ],
              ),
            ),
            SizedBox(height: 5),

            ElevatedButton(
              onPressed: () {
                Navigator.push(context,
                    MaterialPageRoute(builder: (context) => ChangePasswordScreen()));
              },
              style: ElevatedButton.styleFrom(
                primary: Colors.blueGrey,
                padding: EdgeInsets.symmetric(vertical: 12),
              ),
              child: Text('Change Password',
                  style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
            ),
          ],
        ),
      ),
    );
  }
}
